version: '3.9'
services:
  db:
    restart: always
    image: postgres:13
    container_name: podfinder-postgres 
    env_file:
      - '.env'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: