version: '3.9'
services:
  db:
    restart: always
    image: postgres:13
    container_name: podfinder-postgres 
    env_file:
      - '.env'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    container_name: podfinder-redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

volumes:
  postgres_data: