# Generated by Django 4.2.1 on 2023-08-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=24)),
                ('video_filter', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=11, unique=True)),
                ('title', models.CharField(max_length=125)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('times_clicked', models.IntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('error_occurred', models.BooleanField(default=False)),
                ('published_date', models.DateField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcast')),
            ],
        ),
    ]
