# Generated by Django 4.2.1 on 2023-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
