# Generated by Django 4.2.1 on 2023-08-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='error_occurred',
            field=models.BooleanField(default=False),
        ),
    ]
