# Generated by Django 4.2.1 on 2023-05-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_episode_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='transcript_with_time',
        ),
    ]
