# Generated by Django 4.2.1 on 2023-09-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_episode_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='private_video',
            field=models.BooleanField(default=False),
        ),
    ]
