# Generated by Django 4.2.1 on 2023-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_episode_error_occurred'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
