# Generated by Django 4.2.1 on 2023-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_podcast_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='has_add_back_catalogue_ran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='run_auto_add_back_catalogue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='run_get_new_episodes',
            field=models.BooleanField(default=True),
        ),
    ]
