# Generated by Django 4.2.1 on 2023-09-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_episodereleaseday'),
        ('podcasts', '0005_podcast_has_add_back_catalogue_ran_and_more'),
    ]

    operations = [
    ]
