# Generated by Django 4.2.1 on 2023-12-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0007_remove_episode_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="exclusive",
            field=models.BooleanField(default=False),
        ),
    ]
