# Generated by Django 4.2.1 on 2024-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0009_remove_episode_times_clicked"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
