# Generated by Django 4.2.1 on 2024-02-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0010_podcast_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
