# Generated by Django 4.2.1 on 2024-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0010_podcast_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
