# Generated by Django 4.2.1 on 2024-03-25 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0011_alter_podcast_slug"),
        ("podcasts", "0011_episode_is_draft"),
    ]

    operations = []
