# Generated by Django 4.2.1 on 2024-03-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0012_merge_0011_alter_podcast_slug_0011_episode_is_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="error_occurred",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="transcript",
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcript", models.TextField(blank=True, null=True)),
                ("error_occurred", models.BooleanField(default=False)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcasts.episode",
                    ),
                ),
            ],
        ),
    ]
