# Generated by Django 4.2.1 on 2024-05-11 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcasts", "0013_remove_episode_error_occurred_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_podcast",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
