# Generated by Django 4.2.1 on 2024-09-29 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0014_alter_podcast_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="owner",
        ),
    ]
