# Generated by Django 4.2.1 on 2024-09-30 22:00

from django.db import migrations, models
import podcasts.models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0015_remove_podcast_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=podcasts.models.upload_to
            ),
        ),
    ]
