# Generated by Django 4.2.1 on 2024-10-03 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0016_alter_podcast_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="has_add_back_catalogue_ran",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="run_auto_add_back_catalogue",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="run_get_new_episodes",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="video_filter",
        ),
    ]
