# Generated by Django 4.2.1 on 2024-10-03 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0017_remove_podcast_has_add_back_catalogue_ran_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="channel_id",
        ),
    ]
