# Generated by Django 4.2.1 on 2025-05-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0018_remove_podcast_channel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodereleaseday",
            name="day",
            field=models.IntegerField(
                choices=[
                    (1, "Sunday"),
                    (2, "Monday"),
                    (3, "Tuesday"),
                    (4, "Wednesday"),
                    (5, "Thursday"),
                    (6, "Friday"),
                    (7, "Saturday"),
                    (8, "Everyday"),
                ],
                default=2,
            ),
        ),
        migrations.CreateModel(
            name="PodcastRSSFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rss_feed_url", models.URLField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="podcasts.podcast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast RSS Feed",
                "verbose_name_plural": "Podcasts RSS Feeds",
            },
        ),
    ]
