# Generated by Django 4.2.1 on 2024-05-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Member", "Member")], max_length=20
            ),
        ),
    ]
