# Generated by Django 4.2.1 on 2024-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0002_alter_membership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("Owner", "Owner"), ("Admin", "Admin"), ("Member", "Member")],
                max_length=20,
            ),
        ),
    ]
