# Generated by Django 4.2.1 on 2024-12-27 23:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcasts", "0018_remove_podcast_channel_id"),
        ("organisations", "0003_membership_is_primary_alter_membership_role"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "podcast")},
        ),
    ]
