name: CD

on:
  push:
    branches: ["main"]

jobs:
  CD:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 200m
          script: |
            cd ${{ secrets.FILE_PATH }}
            git pull
            docker compose build --no-cache --compress
            docker compose up -d
